require("sagnikc395.core.keymaps")
require("sagnikc395.core.colorscheme")
require("sagnikc395.core.options")
require("sagnikc395.plugins-setup")
require("sagnikc395.plugins.comment")
require("sagnikc395.plugins.nvim-tree")
require("sagnikc395.plugins.lualine")
require("sagnikc395.plugins.telescope")
require("sagnikc395.plugins.nvim-cmp")
require("sagnikc395.plugins.lsp.mason")
require("sagnikc395.plugins.lsp.lspsaga")
require("sagnikc395.plugins.lsp.lspconfig")
require("sagnikc395.plugins.lsp.null-ls")
require("sagnikc395.plugins.autopairs")
require("sagnikc395.plugins.treesitter")
require("sagnikc395.plugins.gitsigns")

